### ISSUE TITLE
License

### ISSUE THREAD

**Issue by IstoraMandiri** [mhollingshead/ncube#1]
Great work, I am considering using this in a project, but it has no license.

Would you consider adding a permissive license such as MIT to this project, so it can be used by others?

Thank you!

**Comment by mhollingshead** [comment]
Thank you for the reminder! Admittedly, I assumed that, since the code was open source, anyone could use it as they please. But the project should now be [licensed under MIT](https://github.com/mhollingshead/ncube/commit/234fc1a059e2a2a1e1c6c7ee0afbc18fd20e3b54).

**Comment by IstoraMandiri** [comment]
Awesome, thanks!
